remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Azure Developer Resources
description: Links to events, videos, podcasts and other resources useful to Azure developers in the UK
