remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

lang: en-GB
title: Microsoft Apps and AI Resources
description: Current Microsoft resources for AI, agents, applications, automation, data and cloud
